# Generated by Django 5.2.4 on 2025-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(default=True, help_text="Décochez pour rendre le produit indisponible même s'il y a du stock"),
        ),
    ]
